OpenBankingUK/tpp-reference-server

app/setup-account-request/obtain-token.js, package-lock.json, package.json, test/setup-account-request/obtain-token.test.js
Add function that requests token from a provided authorised server URI.
Throws error when request is not successful.
To be used later for setup account request flow.
Part of #CDRW-685
=> Add function to request token for account request setup

app/ob-directory.js
Store config from OB Directory under obDirectoryConfig key in AUTH_SERVER_COLLECTION.
Completes: REFAPP-78
=> Add obDirectoryConfig key to AUTH_SERVER_COLLECTION items

app/persistence.js, app/session.js, test/index.test.js, test/ob-directory.test.js
To fix potential race condition, make session `deleteAll()` function `async` and `await` it to finish in test teardowns.
=> Await session deleteAll() in test teardowns - REFAPP-101

app/index.js, app/setup-payment/index.js, app/setup-payment/payment-authorise-consent.js, app/setup-payment/payment-submission.js, app/setup-payment/payments.js, app/setup-payment/persistence.js, app/setup-payment/setup-payment.js, app/setup-payment/submit-payment.js, test/setup-payment/payment-submission.test.js, test/setup-payment/payments.test.js, test/setup-payment/peristence.test.js, test/setup-payment/setup-payment.test.js, test/setup-payment/submit-payment.test.js
- Add new endpoint for payment submission
- Changed/updated persistence
=> Refapp 141 - Payment submission TPP Server endpoint

README.md
Getting latest release `git commands` were unclear so I fixed them.
=> Minor README correction.

.gitignore
Updates to ignore:
* `.env.local`.
* `.env.real`.
=> Minor update of .gitignore

README.md
This PR adds OIDC AISP info into the READMe. Tried to simplify this as much as possible.
* Uses `Curl` to describe the necessary steps.
* Explains how to parse the `state` to conclude the flow.
* Can serve as a template for Payment initiation.
=> REFAPP-169 Update README to include OIDC Authorization Flow for AISP on TPP server.

app/authorisation-servers/authorisation-servers.js, app/authorisation-servers/index.js, app/authorise/authorisation-code-granted.js, app/authorise/index.js, app/authorise/obtain-access-token.js, app/authorise/setup-request.js, app/setup-account-request/setup-account-request.js, app/setup-payment/setup-payment.js, app/setup-request/index.js, app/setup-request/setup-request.js, app/submit-payment/submit-payment.js, test/authorisation-servers/authorisation-servers.test.js, test/authorise/authorisation-code-granted.test.js, test/authorise/obtain-access-token.test.js, test/authorise/setup-request.test.js, test/setup-account-request/setup-account-request.test.js, test/setup-payment/setup-payment.test.js, test/setup-request/setup-request.test.js, test/submit-payment/submit-payment.test.js
- Reduce number of directories by removing `app/setup-request`.
- Reduce files in app root by moving `obtain-access-token.js` to `/authorise` directory.
- Move `resourceServerPath` function to `authorisation-servers.js`.
- Move `createAccessToken` function to `obtain-access-token.js`.
- Move `setup-request.js` to /authorise directory.
=> Refactor setup-request.js - REFAPP-173

app/authorisation-servers/authorisation-servers.js, app/request-data/ob-proxy.js, app/setup-account-request/account-requests.js, app/setup-payment/payments.js, test/authorisation-servers/authorisation-servers.test.js, test/setup-account-request/account-requests.test.js, test/setup-payment/payments.test.js
Move logic to format URI to resourceServerPath function.
=> Keep URI path when using BaseApiDNSUri

README.md
This adds a new sections to the README: `Quick start after Open Banking Directory enrolment`.
Also, updates other sections as necessary.
=> REFAPP-181 Create a separate Live Deploy section in TPP Server README

README.md, app/authorise/authorisation-code-granted.js, app/index.js, test/authorise/authorisation-code-granted.test.js
This PR is the first step for acquiring all data needed to track a user's consent info.
* Changes `authorisationCodeGrantedHandler` to handle POST requests.
* Updates related README entries.
=> REFAPP-192 - Part 1, track user consent 

app/authorisation-servers/authorisation-servers.js, app/authorise/access-tokens.js, app/storage.js, test/storage.test.js
Reverts OpenBankingUK/tpp-reference-server#112
=> Revert "REFAPP-192 Part 2, track user consent "

app/authorise/authorisation-code-granted.js, app/request-data/ob-proxy.js, app/session/session.js, test/authorise/authorisation-code-granted.test.js
Use `getUsername` when relevant in existing code.
=> Add getUsername function to session

README.md, package-lock.json, package.json
This reverts commit 897a73f545e6e2d590106858062ff4a47ca850b1.
=> Revert "Bump version to 0.8.0"

app/setup-account-request/account-requests.js
Move duplicated header setting code to a function.
=> Move account request header setting to function

.env.sample, app/authorise/consents.js, app/ob-directory.js, app/request-data/ob-proxy.js, app/response-logger.js, app/setup-account-request/account-request-authorise-consent.js, app/setup-account-request/account-requests.js, app/setup-payment/payment-authorise-consent.js, app/setup-payment/payments.js, app/submit-payment/payment-submission.js, package-lock.json, package.json, test/authorise/consents.test.js, test/setup-account-request/account-request-authorise-consent.test.js, test/setup-account-request/account-requests.test.js, test/setup-payment/payments.test.js, test/setup-payment/setup-payment.test.js, test/submit-payment/submit-payment.test.js
- When `LOG_ASPSP_RESPONSES=true` log ASPSP API requests and responses to file.
- Include `sessionId` in logs.
- Pass `sessionId` to functions that make ASPSP API requests.
=> Log ASPSP API calls to file - REFAPP-212

app/setup-account-request/account-request-authorise-consent.js, app/setup-account-request/delete-account-request.js, app/setup-account-request/setup-account-request.js, app/setup-payment/payment-authorise-consent.js, app/setup-payment/setup-payment.js, app/submit-payment/payment-submission.js, test/authorise/consents.test.js, test/session/request-headers.test.js, test/setup-account-request/setup-account-request.test.js, test/storage.test.js
Object.assign modifies the first parameter passed to it.
Change first parameter to be a new object to make Object.assign calls idempotent.
=> Make Object.assign calls idempotent

app/authorise/consents.js, app/authorise/index.js, app/request-data/ob-proxy.js, app/setup-account-request/account-request-authorise-consent.js, app/setup-account-request/setup-account-request.js, test/authorise/consents.test.js, test/setup-account-request/account-request-authorise-consent.test.js
Store permissions from successful setup account request response in consent collection.
Log permissions in ASPSP request/response logging.
=> Persist and log permissions from setup account request response

.env.sample, app/index.js, app/request-data/ob-proxy.js, app/validator/fetch-swagger.js, app/validator/index.js, app/validator/init-validator-app.js, app/validator/replay-middleware.js, app/validator/swagger-middleware.js, app/validator/validate-request-response.js, app/validator/validation-error-middleware.js, package-lock.json, package.json, test/index.test.js, test/validator/fixtures/valid-request.js, test/validator/fixtures/valid-response.js, test/validator/validate-request-response.test.js
- Validate against swagger resource API request/response.
- Use `ACCOUNT_SWAGGER` and `PAYMENT_SWAGGER` to configure swagger file location.
- Kafka logging to be done in a future pull request.
=> Add swagger validation of ASPSP resource req/res REFAPP-275

README-VALIDATION.md, README.md
Also add Kafka configuration steps, for logging validation results.
=> Add readme for configuring swagger validation - REFAPP-281

.circleci/config.yml, Dockerfile, index.js, package-lock.json, package.json
Simple upgrade to `^8.11.1`. Works with CircleCI.
=> REFAPP-292 Upgrade to nodejs LTS at v8.11.1

README.md
https://circleci.com/gh/OpenBankingUK/tpp-reference-server/edit#badges
=> circleci status badge

docker-compose.yml
* default to true in `"HEADLESS_CONSENT=true"`.
* add `ACCOUNT_SWAGGER` and `PAYMENT_SWAGGER`.
* set `LOG_ASPSP_RESPONSES`.
* set `"VALIDATION_KAFKA_BROKER=kafka:9092"`.
=> * set `container_name` and `hostname`.

Dockerfile
This PR fixes issues with file access to `./resource.log` on a docker container.
Specifically:
* Remove unnecessary DIR permissions in the `Dockerfile`.
=> Fix file access in docker container

app/session/request-headers.js, app/setup-account-request/account-request-authorise-consent.js, test/session/request-headers.test.js
To be used when using server to perform validation checks on the accounts API calls.
=> Add x-permissions header for setting permissions - REFAPP-314
