OpenBankingUK/tpp-reference-server

README.md, package.json
Based on major merges in the past 14 days on the REPO, this is a draft for the release notes.
```
TPP Reference Server (to read from Mock ASPSP and drive the Client App) written using Express on Node.js:
* Can request token for account request setup
* Added `/account-request-authorise-consent` endpoint for client app.
* Use clientId and clientSecret as credentials to access token endpoint
```
This PR includes:
* Updates to `README`.
* Release version bump.
These are the referenced commits:
* https://github.com/OpenBankingUK/tpp-reference-server/commit/e748162a2c9914fd2439957ba4151bbad46233b4
* https://github.com/OpenBankingUK/tpp-reference-server/commit/b26c531457e51e8e6c6dc141704b6752b4d79466
=> Updates for release v0.3.0

.env.sample, README.md, app/account-request-authorise-consent.js, app/obtain-access-token.js, app/setup-account-request/account-requests.js, app/setup-account-request/setup-account-request.js, test/setup-account-request/account-requests.test.js, test/setup-account-request/setup-account-request.test.js
Add function to POST to `/account-requests` endpoint.
Return accountRequestId from setupAccountRequest function:
- When `/account-requests` response status is `AwaitingAuthorisation` return accountRequestId.
- When `/account-requests` response status is `Rejected` return null for accountRequestId.
Completes: #CDRW-806
=> Call account-requests endpoint after obtaining access-token

app/setup-account-request/account-requests.js, app/setup-account-request/setup-account-request.js, test/setup-account-request/setup-account-request.test.js
For now hardcode API version to v1.1.
In future API version could be manually stored for each authorisationServer TPP registers with.
Debug log payload returned from /account-requests call.
Add Risk field to /account-requests payload to pass swagger schema validation.
=> Add /open-banking/v1.1 prefix to /account-requests call

package-lock.json
Small PR. The version number here needed to be bumped up to `0.3.0` to match `package.json`.
=> Fix version number in package-lock.

app/ob-directory.js, package.json, scripts/list-auth-servers.js, test/scripts/list-auth-servers.test.js
- Add script that prints to console TSV list of auth servers.
- Outputs boolean flag for clientCredentialsPresent and openIdConfigPresent.
- For use to identify authorisation server id when configuring client credentials via another script.
Completes: REFAPP-79
=>  Add listAuthServers script

app/authorisation-servers/authorisation-servers.js, app/authorisation-servers/index.js, app/ob-directory.js, scripts/list-auth-servers.js, test/scripts/list-auth-servers.test.js
- Extract auth server code from ob-directory into new file.
- Update references to moved functions.
- Refactor list auth server test to put stubbing in a function.
A refactoring, in preparation for storing openid config in a later PR.
=> Extract authorisation servers logic into separate file

README.md, app/authorisation-servers/authorisation-servers.js, app/authorisation-servers/index.js, app/authorisation-servers/openid-config.js, app/ob-directory.js, scripts/list-auth-servers.js, test/authorisation-servers/authorisation-servers.test.js, test/ob-directory.test.js, test/storage.test.js
- Add updateOpenIdConfigs() function to fetch and store configs.
- Fetch and store openIdConfig for each authorisation server without openIdConfig.
- Trigger async update of openIdConfigs when client requests ASPSP list (for now this seems a good time to fetch them)
- Await db cleanup to finish in test setups and teardowns
For: REFAPP-45
=> Fetch and store openId configs

README.md, app/authorisation-servers/authorisation-servers.js, app/ob-directory.js, scripts/list-auth-servers.js, test/authorisation-servers/authorisation-servers.test.js, test/ob-directory.test.js, test/scripts/list-auth-servers.test.js
- Use authorisation server `Id` from OB Directory
- Store `OBOrganisationId` and `OrganisationCommonName` in db
- Store `AuthorityId`, `MemberState`, `RegistrationId` in db
- Update list auth server script to print `OBOrganisationId`, `OrganisationCommonName`, `AuthorityId`
- Rename `AUTH_SERVER_COLLECTION` to `ASPSP_AUTH_SERVERS_COLLECTION`
Completes: REFAPP-84
Tested successfully against our mock server, and against OB Directory.
=> Use authorisation server Ids and other data from OB Directory

app/authorisation-code-granted.js, app/authorisation-servers/openid-config.js, app/ob-directory.js, test/authorisation-code-granted.test.js, test/index.test.js
This is more than a config update. Calls to MTLS `superagent` where incorrect.
This is now fixed with other tidy up.
I've added the `CA`, `CERT` and `KEY` related ENVs. And, as soon as this PR is approved, I'll update `MTLS_ENABLED` to true.
See below to confirm `Ozone` both have OpenId Config,
__Referenco Bank__
```sh
$ npm run listAuthServers | grep Referenco
48fr7qwRKzA0eWKR2Se8YR	Referenco Bank	Referenco Bank - ASPSP	GB:FCA:RegBancomamaApp01	4iZQesHhScgRdgnWwE	false	true
```
__Modelo Bank__
```sh
$ npm run listAuthServers | grep Modelo
4khj4NmBD8lQxmLh2O9FLY	Modelo Bank	Modelo Bank - ASPSP	GB:FCA:RegBancopapaApp01	7umx5nTR33811QyQfi	false	true
```
=> REFAPP-90 - Configure MTLS in heroku to get Ozone openIdConfig

.env.sample, README.md, app/account-request-authorise-consent.js, app/authorisation-code-granted.js, app/authorisation-servers/authorisation-servers.js, app/authorisation-servers/index.js, app/obtain-access-token.js, app/setup-account-request/setup-account-request.js, test/account-request-authorise-consent.test.js, test/authorisation-code-granted.test.js, test/authorisation-servers/authorisation-servers.test.js, test/authorise/request-jws.test.js, test/obtain-access-token.test.js, test/setup-account-request/setup-account-request.test.js
- Add functions to get `authorisationEndpoint` and `tokenEndpoint` by auth server id from openid config in db.
- Use these functions instead of `ASPSP_AUTH_SERVER` env var to construct API calls.
- These functions throw errors if configuration not found.
Completes: REFAPP-86
=> Use auth and token endpoints from  openid config - REFAPP-86 

app/authorisation-servers/authorisation-servers.js, test/ob-directory.test.js
Test modified - separate task - decouple the code to untangle the caching etc and make the credentials adding testable
=> Ref #REFAPP-42 Return only ASPSP Authorisation Servers with Client Credentials Registered

README.md, app/account-request-authorise-consent.js, app/obtain-access-token.js, app/setup-account-request/setup-account-request.js, app/storage.js, test/account-request-authorise-consent.test.js
- Add how to set client credentials for mock server to readme
- Log mongodb URI for debugging
- Use correct getClientCredentials function for /authorize URL creation
- Add MONGODB_URI setting to script examples in readme
- Use new dummy data ids from mock server in readme examples
=> Various client credentials fixes and readme changes

README.md
- Explain heroku client credentials configuration for mock server integration.
- This can be reworded later, just wanted to capture it now.
=> Add client credentials config for heroku to readme

README.md, app/ob-directory.js, package.json, scripts/update-auth-server-and-open-id-configs.js, test/scripts/update-auth-server-and-open-id-configs.test.js
This moves caching of Auth server and OpenId configs logic to a standalone script.
* Added script.
* Added spec.
* Updated `package.json` to include new script.
* Updated `README` to include new script details.
=> REFAPP-103 Create a script to bootstrap AuthServer & OpenID Config

app/account-request-authorise-consent.js, app/authorisation-servers/authorisation-servers.js, app/authorise/request-jws.js, app/setup-account-request/setup-account-request.js, test/account-request-authorise-consent.test.js, test/authorise/request-jws.test.js
- Add `/open-banking` prefix to resource URL only when needed.
- Some authorisation server configs already have `/opening-banking/v1.1` prefix on `BaseDNSUri` field.
- Fix claim field names to `request_uri` and `client_id`.
- Correct values for `aud` and `iss` in JWS claims.
- Set `aud` and `iss` from perspective of TPP client.
- Hardcode ignoring of OB Directory test `openidConfigUrl`.
=> Various fixes to JWS claims and resource server URI

app/setup-account-request/setup-account-request.js, test/setup-account-request/setup-account-request.test.js
- Pick up `AccountRequestId` from correct location in response payload.
- Throw error when account request response `Status` is `Rejected` or `Revoked`.
- Throw error when account request response `Status` or `AccountRequestId` not found in payload.
=> Fix and improve account request response handling

app/account-request-authorise-consent.js, test/account-request-authorise-consent.test.js
- Change response status from `302` to `200` for successful `/account-request-authorise-consent` response.
- As in browser we can't intercept a `302` response.
- This requires corresponding change be merged on `tpp-reference-client`: https://github.com/OpenBankingUK/tpp-reference-client/pull/31
=> Change account request response status to 200

app/authorisation-code-granted.js, app/authorise/access-tokens.js, app/authorise/index.js, app/index.js, test/authorisation-code-granted.test.js, test/authorise/access-tokens.test.js
Store token payload from authorisation code request under session ID in mongodb.
For now there is no flushing of expired tokens. Can be added later.
=> Store access token response under session ID

app/setup-account-request/setup-account-request.js, app/setup-request/index.js, app/setup-request/setup-request.js, test/setup-account-request/setup-account-request.test.js
- Refactor generic setup request logic into `app/setup-request/setup-request.js`.
- Pass `createRequestFn` as parameter to new generic `makeRequest` function.
- Set scopes to `accounts payments` for `client_credentials` grant.
- Intention is this code be reused for payments request.
=> Make setup request logic generic for reuse by payments

app/authorise/authorise-uri.js, app/setup-account-request/account-request-authorise-consent.js, app/setup-payment/payment-authorise-consent.js, test/setup-account-request/account-request-authorise-consent.test.js, test/setup-payment/payment-authorise-consent.test.js
- In preparation for `interactionId` to be used to store information required to make request later in flow.
=>  Set interactionId in state in /auth redirect uri REFAPP-97

README.md, app/authorisation-servers/authorisation-servers.js, app/authorisation-servers/index.js, app/request-data/ob-proxy.js, app/setup-account-request/account-request-authorise-consent.js, app/setup-payment/payment-authorise-consent.js, app/setup-payment/payment-submission.js, test/authorisation-servers/authorisation-servers.test.js, test/setup-account-request/account-request-authorise-consent.test.js, test/setup-payment/payment-authorise-consent.test.js, test/setup-payment/payment-submission.test.js
- When handling requests lookup `fapiFinancialId` using the `authServerId`.
- Client now no longer needs to set `x-fapi-financial-id` header.
=> Lookup fapiFinancialId REFAPP-142

README.md, app/authorisation-servers/authorisation-servers.js, test/ob-directory.test.js, test/storage.test.js
Client no longer needs to know about `orgId/fapiFinancialId`.
=> No longer send ASPSP orgId to client

app/setup-account-request/setup-account-request.js, app/setup-payment/payment-authorise-consent.js, app/setup-payment/setup-payment.js, app/setup-payment/submit-payment.js, app/setup-request/setup-request.js, test/setup-request/setup-request.test.js
The `accessTokenAndResourcePath` function does not require `fapiFinancialId`.
=> No longer pass fapiFinancialId to accessTokenAndResourcePath

README.md, app/authorisation-servers/authorisation-servers.js, app/authorisation-servers/index.js, app/index.js, app/setup-account-request/account-request-authorise-consent.js, app/setup-payment/payment-authorise-consent.js, app/setup-request/setup-request.js, test/index.test.js, test/setup-account-request/account-request-authorise-consent.test.js, test/setup-payment/payment-authorise-consent.test.js, test/setup-request/setup-request.test.js
- Add middleware to check `x-authorization-server-id` header.
- For consistency, always obtain authServerId from `x-authorization-server-id` header, instead of from posted JSON payload.
- Add `x-authorization-server-id` to examples in readme.
Tested locally with client e2e tests.
=> Use x-authorization-server-id header REFAPP-155

README.md, package-lock.json, package.json, scripts/update-auth-server-and-open-id-configs.js
* Started using [dotenv](https://www.npmjs.com/package/dotenv) to load ENVs from `.env` file.
* Added better debugging and logging for easier triage.
* README updates.
=> REFAPP-147 `updateAuthServersAndOpenIds` should load ENVs from .env file.

README.md, scripts/list-auth-servers.js
* `listAuthServers` now uses [dotenv](https://www.npmjs.com/package/dotenv).
* Updates related details in `README`.
=> REFAPP-158 `listAuthServers` should load ENVs from .env file.

README.md, scripts/add-client-credentials.js
* `saveCreds` now uses [dotenv](https://www.npmjs.com/package/dotenv).
* Updates related details in `README`.
=> REFAPP-159 `saveCreds` should load ENVs from .env file.

app/setup-account-request/account-requests.js, app/setup-payment/payments.js, test/setup-account-request/account-requests.test.js, test/setup-payment/payments.test.js
As this header is optional in v1.1.1 of specs.
Tested successfully against reference bank.
=> Make x-jws-signature header optional

.env.sample, README.md, app/index.js, app/session/authorization.js, app/session/session.js
Also
- Remove unused `session/check` route, and remove `session.check` function.
- Remove unneeded `AUTHORIZATION` env var.
- Rename `getAuthFromSession` function to `validSession`, returns `true` when session exists, otherwise `false`.
- Use `validSession` to check authorization header represents valid session id.
=> Ref #REFAPP-112 Allow Multiple Sessions

README-HEROKU.md, README.md
- To make root readme file easier to read.
- Link from root readme to heroku readme.
=> Move heroku instructions to separate readme file

README.md
This re-works the `README` to introduce a Quick Start section when running with the mock server.
Ignore other sections for now as they will be updated for the running with OB Directory use cases in an upcoming PR.
=> REFAPP-180 Create a separate Mock Server section in TPP Server README

app/authorisation-servers/authorisation-servers.js
Previously we did not retrieve OpenID config when we already had a cached copy.
For REFAPP-60.
=> Retrieve OpenID config on every update - REFAPP-60

app/authorise/access-tokens.js, app/authorise/authorisation-code-granted.js, app/request-data/ob-proxy.js, app/session/authorization.js, app/session/session.js, test/authorise/access-tokens.test.js, test/authorise/authorisation-code-granted.test.js, test/index.test.js
This PR completes https://openbanking.atlassian.net/browse/REFAPP-189.
* Ensures all calls to `setTokenPayload` use the username from the current session.
* Ensures all calls to `accessToken` use the username from the current session.
We can now track the consent token. Sample data from MongoDB.
```
> db.accessTokens.find().pretty()
{
"_id" : ObjectId("5a6616f1464ce958915b6c48"),
"id" : "alice",
"access_token" : "2YotnFZFEjr1zCsicMWpAA",
"expires_in" : 3600,
"token_type" : "bearer"
}
```
=> REFAPP-189 Part 2, Track active consent ttl in /tpp/authorized redirection 

app/authorise/authorise-uri.js, test/setup-account-request/account-request-authorise-consent.test.js
This (tiny) PR simplifies storing the `AccountRequestId` as part of the consent details.
As part of the state payload,
* The `AccountRequestId` will be passed back to the server from the client.
* The `AccountRequestId`will accompany other required consent details in same request.
* This allows us to persist all consent details in one transaction.
* And, ensures that we only track data after a successful consent attempt.
=> REFAPP-191 Part 1 - Add AccountRequestId to state payload

app/authorisation-servers/authorisation-servers.js, app/authorise/access-tokens.js, app/storage.js, test/storage.test.js
This PR extends the storage `get` method to findOne based on a query.
This allows for composite key queries which are required for the new consents collection.
=> REFAPP-192 Part 2, track user consent 

app/authorise/authorisation-code-granted.js, app/authorise/consents.js, app/authorise/index.js, app/request-data/ob-proxy.js, test/authorise/authorisation-code-granted.test.js, test/authorise/consents.test.js, test/index.test.js
This PR:
* Completes work on tracking a user's consent.
* It uses `access_token` related to a given consent.
* Its an end to end solution and works against proxied accounts endpoints.
Consent is indexed using a composite key that is a concatenated string made up of `username:::authorisationServerId:::scope`.
=> REFAPP-192 track user consent

.gitignore, app/authorisation-servers/authorisation-servers.js, app/authorise/consents.js, app/authorise/index.js, app/index.js, app/ob-directory.js, test/authorisation-servers/authorisation-servers.test.js, test/authorise/consents.test.js, test/ob-directory.test.js
- Add `filterConsented` function to filter auth server ids that user has consent with for given scope.
- Add `accountsConsentGranted` field to ASPSP list payload, to be used by client.
Note: Ignores `expirationDateTime` for now when determining consent is present. To be added in a future PR.
=>  Add accountsConsentGranted field to ASPSP list payload - REFAPP-191

app/authorise/consents.js, app/authorise/index.js, app/index.js, app/setup-account-request/account-request-authorise-consent.js, app/setup-account-request/account-requests.js, app/setup-account-request/delete-account-request.js, app/setup-account-request/index.js, app/setup-account-request/setup-account-request.js, app/storage.js, test/authorise/consents.test.js, test/setup-account-request/account-request-authorise-consent.test.js, test/setup-account-request/account-requests.test.js, test/setup-account-request/delete-account-request.test.js, test/setup-account-request/setup-account-request.test.js
- Add `/account-request-revoke-consent` endpoint.
- Calling endpoint:
- Calls DELETE `/account-requests/${accountRequestId}` on ASPSP's server.
- Deletes consent object from TPP servers consents collection.
- Some tidy up of passing headers to account request functions.
=> Add revoke accounts consent endpoint REFAPP-201

app/authorise/consents.js, app/setup-account-request/account-requests.js, test/authorise/consents.test.js, test/setup-account-request/account-requests.test.js
- Pass headers to make consistent with other account request functions.
- Verify headers and set x-fapi-interaction-id header on requests.
=> Pass headers as object to getAccountRequest

app/authorisation-servers/openid-config.js
- The openid config endpoints are no longer going to be MTLS protected.
- Tested successfully against reference bank.
**Note: reference bank openid conf endpoint has changed**.
Run `DEBUG=debug,log npm run updateAuthServersAndOpenIds` to update openid conf if required.
=> Remove MTLS setup from openid config endpoint call

app/session/index.js, app/session/session.js, app/submit-payment/payment-submission.js, app/submit-payment/submit-payment.js, test/submit-payment/payment-submission.test.js, test/submit-payment/submit-payment.test.js
It was incorrect to use the client credentials access token when
calling the /payment-submissions endpoint.
=> Use auth code grant access token for /payment-submissions call

app/submit-payment/payment-submission.js
- Fix invalid token value being sent on /payment-submissions call.
- The consentAccessToken() is async so need to await to obtain token.
=> Await consentAccessToken to obtain token

app/request-data/ob-proxy.js, app/session/index.js, app/session/request-headers.js, app/setup-account-request/account-request-authorise-consent.js, app/setup-account-request/delete-account-request.js, app/setup-payment/payment-authorise-consent.js, app/submit-payment/payment-submission.js, test/session/request-headers.test.js, test/setup-account-request/account-request-authorise-consent.test.js, test/setup-account-request/delete-account-request.test.js, test/setup-payment/payment-authorise-consent.test.js, test/submit-payment/payment-submission.test.js
- Move extract headers logic into a separate function.
- Replace duplicated code with calls to extractHeaders function.
- Makes it easier to add new request headers later (e.g. a permissions list header).
=> Refactor extract headers - REFAPP-212 

app/setup-account-request/account-request-authorise-consent.js, app/setup-account-request/account-requests.js, app/setup-account-request/setup-account-request.js, test/setup-account-request/account-request-authorise-consent.test.js, test/setup-account-request/account-requests.test.js, test/setup-account-request/setup-account-request.test.js
- Pass account permissions in headers object.
- In future we may allow permissions to be set by client via a request header.
- Return permissions from ASPSP response to account request setup.
=> Return permissions from account request setup - REFAPP-212

app/authorise/consents.js, test/authorise/consents.test.js
When setting consent in store keep permissions when they are already in store and accountRequestId is the same.
=> Keep permissions from account request when storing consent

app/authorise/consents.js, app/request-data/ob-proxy.js, app/response-logger.js, app/session/request-headers.js, app/setup-account-request/account-request-authorise-consent.js, app/setup-account-request/account-requests.js, app/setup-account-request/delete-account-request.js, app/setup-account-request/setup-account-request.js, app/setup-payment/payment-authorise-consent.js, app/setup-payment/payments.js, app/submit-payment/payment-submission.js, test/authorise/consents.test.js, test/index.test.js, test/session/request-headers.test.js, test/setup-account-request/account-request-authorise-consent.test.js, test/setup-account-request/delete-account-request.test.js, test/setup-account-request/setup-account-request.test.js, test/setup-payment/payment-authorise-consent.test.js, test/submit-payment/payment-submission.test.js
Required some tidy and minor refactoring.
It now adds the `authorisationServerId` to entries in the `resource.log`.
For example:
```
{
"name": "ob-proxy.log",
"hostname": "Ezos-MacBook.local",
"pid": 3766,
"origin": "superagent",
"req_id": "1519231934075-21437101916908774",
"interactionId": "44394c83-e5f6-4071-901b-09bdb64de224",
"sessionId": "910d9530-1727-11e8-ac27-45a8588a3523",
"authorisationServerId": "aaaj4NmBD8lQxmLh2O",
"level": 30,
"req": {
"method": "POST",
"url": "http://localhost:8001/open-banking/v1.1/payments",
"path": "/open-banking/v1.1/payments",
"headers": {
"User-Agent": "node-superagent/3.8.0",
"authorization": "Bearer 2YotnFZFEjr1zCsicMWpAA",
"x-fapi-financial-id": "aaax5nTR33811Qy",
"x-fapi-interaction-id": "44394c83-e5f6-4071-901b-09bdb64de224",
"x-idempotency-key": …
```
=> REFAPP-222 Add authorisation server id to TPP server response log.

app/authorisation-servers/authorisation-servers.js, app/authorisation-servers/index.js, package.json, scripts/list-auth-servers.js, scripts/register-aspsp-client-config.js, test/authorisation-servers/authorisation-servers.test.js, test/scripts/list-auth-servers.test.js, test/scripts/register-aspsp-client-config.test.js
This work bridges a gap showcased by the new `auto-login` work.
__Problem__
* Using OpenId Config params directly is not always correct.
* There's a direct mapping between a TPP's client credentials and ASPSP supported configurations for that client.
* This mapping happens either manually or very soon dynamically.
With Ozone, this has been a manual process. It highlighted an issue based on one client supporting `PS256` signing for `auto-login` during `createJsonWebSignature` while the older client supporting `none`.
__This PR__
* We now have a script that manually registers the agreed upon `AuthServer` OpenId config.
* In our particular case, `createJsonWebSignature` uses the correct signing algo.
=> REFAPP-225 Manually Register Agreed AuthServer Client Config

app/authorisation-servers/authorisation-servers.js, app/authorisation-servers/index.js, package.json, scripts/list-auth-servers.js, scripts/register-aspsp-client-config.js, test/authorisation-servers/authorisation-servers.test.js, test/scripts/list-auth-servers.test.js, test/scripts/register-aspsp-client-config.test.js
Technically, client credentials are tied to a specific `SOFTWARE_STATEMENT_ID` that relationship was implicit.
This PR aims to make this relationship explicit. Especially,
* To clearly explain which software statement corresponds to which credentials.
* To make it easier to debug issues with upstream ASPSPs.
* To clarify how the latest Ozone updates can trigger specific features based on a `client_id` + `SOFTWARE_STATEMENT_ID` combo.
* To simplify local testing. Making swapping AuthServers and Credential features easier.
=> REFAPP-225 Credentials scoped by software statement

app/authorisation-servers/authorisation-servers.js
When user has old clientCredentials object replace it with an array.
=> Make clientCredentials an array on saveCreds script run

app/ob-util.js, app/setup-account-request/account-requests.js, app/validator/index.js, app/validator/validate-request-response.js, app/validator/validation-error-middleware.js, test/index.test.js, test/validator/validate-request-response.test.js
- Various refactoring in prep for change.
- Write output including validation report to kakfa log.
- Previously we hadn't included validation results in the kakfa log.
- Return validation report object from `validate` function, instead of HTTP response object.
=> Write output including validation report to kakfa - REFAPP-281

index.js
- Heroku dynamically sets the `PORT` env var.
- For Heroku deployment to work we need to listen on `PORT`, and not set host to '0.0.0.0'.
- Fix is to listen on `PORT` when `TPP_REF_SERVER_PORT` env var is not set.
=> Use PORT when TPP_REF_SERVER_PORT not set to fix Heroku deploy

docker-compose.yml
These are the same `ENV` variables configured in `.env.sample`.
* Added missing env variables.
* Made VALIDATE_RESPONSE configurable without having to edit the docker-compose.yml.
=> Include validation in docker-compose config.
